version: "3"

services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000