personality_description_list = [
	"Extremely introverted and shy. Very calm and emotionally stable. Thinks in abstract theories.Disorganized and scattered.",
	"Deeply introverted and inward focused. Extremely even-tempered. Values independence andspontaneity. Dislikes rigid rules.",
	"Very introverted but content with own company. Excellent at keeping emotions in check.Appreciates structure and routine.",
	"Rarely speaks out in groups. Remarkably serene and stable. Demands precision andmeticulous organization. Inflexible thinking.",
	"Quiet loner who avoids attention. Steady and calm under normal circumstances. Forgetfuland lacks focus or planning.",
	"Introvert who needs solitary time to recharge. Composed emotional state. Chafes at excessiverules and restrictions.",
	"Prefers own company but cordial when engaged. Even-tempered with occasional frustration.Likes structure for productivity.",
	"Painfully shy and uncomfortable socially. Slow to anger but irritation builds. Demanding ofself and extremely organized.",
	"Avoids social situations to prevent emotional turmoil. Freely expresses passion when riled.Often loses track of things.",
	"Retreats from the world to process strong feelings alone. Passionate about causes but rebelsagainst control.",
	"Withdraws to deal with emotions privately. Feelings oscillate frequently. Takes comfort inroutines and planning. ",
	"Socially withdrawn due to performance anxiety. Extremely sensitive and volatile moods.Meticulous and inflexible methods.",
	"Paralyzed by shyness and anxiety. Highly unstable emotions. Forgetful and often loses things.",
	"Hermit-like due to social phobia. Tumultuous feelings and frequent panic. Bucks against anysort of system or control.",
	"Avoids people to prevent overwhelming anxiety. Emotionally fragile. Reliant on routines tomanage chaos internally.",
	"Socially paralyzed by intense anxiety. Moods constantly shifting. Strict organization providesa sense of control.",
	"Introverted and independent. Extremely patient and calm. More theoretical than practical.Often messy and disorganized.",
	"Values solitude and freedom. Highly composed with even temper. Resists schedules, rules,and rigid structure.",
	"Prefers working solo. Serene and stable even under high stress. Appreciates structuredapproach to productivity.",
	"Prefers own company. Highly self-possessed with unflappable calm. Demanding standards ofprecise order and quality.",
	"Introverted and enjoys solitude. Fairly relaxed unless strongly provoked. Often loses track ofthings or forgets obligations.",
	"Independent; avoids crowds and small talk. Calm except for occasional grumpiness. Chafes atrules and constraints.",
	"Likes working alone. Even-tempered and focused. Makes steady progress with semistructured approach.",
	"Aloof and prefers own company. Represses anger leading to occasional outbursts. Demandsrigorously high standards.",
	"Avoids crowds which magnify emotions. Passionate internally. Often sidetracked andforgetful.",
	"Solitary rebel unwilling to conform. Passions run hot then cold. Hates rules interfering withindependence.",
	"Works alone to avoid emotional chaos of groups. Intense feelings dominate inner life.Outwardly functional and productive.",
	"Prefers solitude to avoid stirring emotions. Prone to volatile mood swings. Thrives on strictlycontrolled environment.",
	"Isolates self to minimize anxiety triggers. Hypersensitive and unstable emotions. Easilydistracted and disorganized.",
	"Avoids interactions to prevent emotional meltdowns. Constant but unpredictable moodfluctuations. Resists any constraints.",
	"Works alone to prevent overwhelming anxiety. Frequently upset and high-strung. Routineand order create sense of stability.",
	"Prefers solitude due to crippling social anxiety. Extremely volatile emotions. Strict rules andorder feel safer.",
	"Vivacious and friendly with groups. Unflappable calm even in chaos. Thinks imaginatively butforgets practical matters.",
	"Thrives on meeting new people. Extremely even-keeled emotionally. Hates routine andrefuses to be controlled.",
	"Lively and outgoing. Remarkably composed under stress. Appreciates structured routinearound socializing.",
	"Gregarious and lively in crowds. Imperturbable mood regardless of circumstances. Demandsmeticulous organization.",
	"Loves chatting and meeting people. Mild emotions unless seriously provoked. Forgetsobligations and details.",
	"Gregarious and friendly. Generally calm and steady. Resists strictly following rules androutine.",
	"Thrives on social connections. Calm demeanor with occasional grumpiness. Likesorganization for optimal productivity.",
	"Outgoing and vivacious. Slow to anger but can become very irritated. Insists upon strict rulesand order at all times.",
	"Loves big lively groups. Freely expresses passion and excitement. Forgetful and makes plansbut doesn't follow through.",
	"Thrives on meeting people and trying new things. Passionate and changeable moods. Hatesbeing controlled or restricted.",
	"Lively and gregarious. Prone to powerful but fluctuating emotions. Enjoys organization mixedwith spontaneity.",
	"Outgoing and expressive. Intense but variable feelings. Demands strict structure and routinearound socializing.",
	"Loves social interaction despite anxiety it causes. Highly emotionally fragile. Disorganizedand forgetful.",
	"Very outgoing but crowds drain nervous energy. Emotionally volatile. Resists rules androutine rigidly imposed.",
	"Enthusiastic people person but anxious. Prone to unpredictable mood swings. Routine helpsmanage emotions.",
	"Outgoing and talkative but often overwhelmed. Extremely unstable moods. Strict control andorder feel safer.",
	"Ultimate extrovert the center of attention. Remarkably tranquil even amidst chaos. Forgetfulof practical matters.",
	"Thrives as undisputed life of any party. Extremely even temperament. Hates any restrictions.",
	"The more people the better. Immensely level-headed. Appreciates routine that allows beingsocial.",
	"Ultimate social butterfly. Imperturbable emotional state. Demands strict order andmeticulous planning.",
	"Wildly outgoing and friendly. Generally calm except for occasional grumpy spells. Forgetsobligations.",
	"Center of attention. Pretty even-keeled emotionally. Chafes against excessive rules andcontrol.",
	"Truly energetic extrovert. Mostly steady mood. Enjoys organization that facilitates activities.",
	"Non-stop chatterbox. Represses anger leading to blow ups. Demands rigorously structuredenvironment.",
	"Thrives on excitement and crowds. Emotions change rapidly like a thrill ride. Forgetful anddisorganized.",
	"Center of fun and excitement. Emotionally passionate and changeable. Resists anyconstraints.",
	"Functions best as dynamic hub of activity. Intense emotions range widely. Appreciatesstructured routine.",
	"Ultimate social butterfly. Feelings amplify from ecstasy to despair rapidly. Demands rigidorder.",
	"Chaotic social fun masks anxiety. Emotions easily spiral out of control. Disorganized andforgetful.",
	"Revels in social excitement but finds it draining. Extreme emotional volatility. Resists anycontrol fiercely.",
	"Loves crowds but they stir up nervous energy. Unpredictable emotional rollercoaster. Routinestabilizes.",
	"Social exuberance masks overwhelming anxiety. Extremely fragile and unstable emotions.Strict order feels safest."
]