version: "3"

services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  backend-core:
    env_file:
      - ./backend/core/.env
    build:
      context: backend/core
      dockerfile: Dockerfile
    container_name: backend-core
    restart: always
    volumes:
      - ./backend/core/:/code/
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - 5050:5050
  backend-private:
    env_file:
      - ./backend/private/.env
    build:
      context: backend/private
      dockerfile: Dockerfile
    container_name: backend-private
    restart: always
    volumes:
      - ./backend/private/:/app/
    ports:
      - 5051:5050
